# Generated by Django 3.2.5 on 2021-08-23 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20210823_1940'),
        ('users', '0002_auto_20210821_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followees',
            field=models.ManyToManyField(related_name='_users_user_followees_+', through='instagram.FriendShip', to=settings.AUTH_USER_MODEL, verbose_name='フォロー中のユーザー'),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_users_user_followers_+', through='instagram.FriendShip', to=settings.AUTH_USER_MODEL, verbose_name='フォローされているユーザー'),
        ),
    ]
