# Generated by Django 3.2.5 on 2021-08-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenttopost',
            old_name='user',
            new_name='author',
        ),
    ]
