# Generated by Django 3.2.5 on 2021-08-16 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='atuhor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 16, 7, 4, 10, 877428, tzinfo=utc), null=True),
        ),
    ]
