# Generated by Django 3.2.5 on 2021-08-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tag',
        ),
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
