# Generated by Django 3.2.5 on 2021-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20210830_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='post', to='instagram.Posts'),
        ),
    ]
