# Generated by Django 3.2.5 on 2021-08-24 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20210823_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
