# Generated by Django 3.2.5 on 2021-08-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_posts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='tag',
        ),
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='instagram.Tag'),
        ),
    ]
