# Generated by Django 3.2.5 on 2021-08-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_postlikes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
