# Generated by Django 3.2.5 on 2021-08-21 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20210821_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 21, 7, 55, 34, 907392, tzinfo=utc), null=True),
        ),
    ]
