# Generated by Django 3.2.5 on 2021-08-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
