# Generated by Django 3.2.5 on 2021-08-22 01:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20210822_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 22, 1, 34, 58, 298941, tzinfo=utc), null=True),
        ),
    ]
