# Generated by Django 3.2.5 on 2021-08-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_auto_20210829_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tag',
        ),
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='instagram.Tag'),
        ),
    ]
