# Generated by Django 3.2.5 on 2021-08-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_auto_20210829_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerated_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.posts')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.tag')),
            ],
        ),
    ]
