# Generated by Django 3.2.5 on 2021-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_posttagrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tag',
        ),
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, through='instagram.PostTagRelation', to='instagram.Tag'),
        ),
    ]
