# Generated by Django 3.2.5 on 2021-08-30 04:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_auto_20210829_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
